/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-04-01 10:00:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"/js/jquery-3.4.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar myChatRoom = \"\";\n");
      out.write("\n");
      out.write("\t$(window).on('load', function() {\n");
      out.write("\n");
      out.write("\t\t//전체 채팅방 리스트 가져오기\n");
      out.write("\t\tgetRoomList();\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t//전체 채팅방 리스트 가져오기\n");
      out.write("\tfunction getRoomList() {\n");
      out.write("\n");
      out.write("\t\t//Ajax 호출\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : '/chat/roomList.do',\n");
      out.write("\t\t\ttype : 'post',\n");
      out.write("\t\t\tdataType : \"JSON\",\n");
      out.write("\t\t\tcontentType:\"application/json; charset=UTF-8\",\n");
      out.write("\t\t\tsuccess : function(json) {\n");
      out.write("\n");
      out.write("\t\t\t\tvar roomList = \"\";\n");
      out.write("\n");
      out.write("\t\t\t\tfor (var i = 0; i < json.length; i++) {\n");
      out.write("\t\t\t\t\troomList += (json[i] + \"<br>\");\n");
      out.write("\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t$('#room_list').html(roomList);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<h1>채팅방 전체 리스트</h1>\n");
      out.write("\t<hr />\n");
      out.write("\t<div id=\"room_list\"></div>\n");
      out.write("\t<br />\n");
      out.write("\t<br />\n");
      out.write("\t<h1>채팅방 입장 정보</h1>\n");
      out.write("\t<hr />\n");
      out.write("\t<form name=\"form\" method=\"post\" action=\"/chat/intro.do\">\n");
      out.write("\t\t채팅방 이름 : <input type=\"text\" name=\"room_name\" id=\"room_name\" /> <br />\n");
      out.write("\t\t채팅자 이름 : <input type=\"text\" name=\"user_name\" id=\"user_name\" /> <br />\n");
      out.write("\t\t<input type=\"submit\" value=\"입장\" />\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
